### ISSUE TITLE
Refactor link_generator.py

### ISSUE THREAD

**Issue by bianjiang** [ufbmi/onefl-deduper#9]
Currently, the logic is hard-coded to deal with two hashes.

Need to consider more than two hashes, in a future release.

**Comment by indera** [comment]
This is a good idea and I placed a todo item in the code for this exact purpose

https://github.com/ufbmi/onefl-deduper/blob/3064c3985b39b462ee5944b867dfea16602c4550/onefl/link_generator.py#L140

If we add more hashes we would still have to create logic on how to re-conciliate all cases -- so far I don't see clearly how it can be generalized.

**Comment by bianjiang** [comment]
Right, I agree.   We will need to sit down talk about this part after this round.  It might come sooner, but let's see.  I think it's possible (have some sense of how this can be done).
